#pragma config(Sensor, port2,  ArmBottomBumper, sensorVexIQ_Touch)
#pragma config(Sensor, port3,  Main_Gyro,      sensorVexIQ_Gyro)
#pragma config(Sensor, port4,  LED,            sensorVexIQ_LED)
#pragma config(Sensor, port7,  CenterColor,    sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port8,  CrossColor,     sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port12, BallDetect,     sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          Left,          tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          Intake,        tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          Right,         tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor9,          CubeClaw,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor10,         ArmRight,      tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,         ArmLeft,       tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//VIQC_SquaredAway_CompCode
/*************************************PROGRAMMER NOTES*****************************************************//*
/*1*//* get odometry working
/*2*//*
/*3*//*
/*4*//*
/*5*//*
/*6*//*
/*7*//*
/*8*//*
/*9*//*
/*10*//*
/*11*//*
/*12*//*
/*13*//*
/*14*//*
/*15*//*
*//*End of Notes Main Program Code is Below */

int PickupBonusSequenceState;
int PlaceBonusSequenceState;

bool intakeStarted;

float Height0 = 0; //Floor
float Height1 = -100; //Place HighScored Hub and Move MultiPusher Over Field Lines
float Height2 = -200; //Position HighScored Hub
float Height3 = -300; //Static Height / Moving height for balance
float Height4 = -500; //Bonus Hub Position
float Height5 = -680; //Bonus Hub PickUp
int ArmPresetValue = 0; // the preset number that tells the preset code how high to move the arm

void driveDistance(float distance) {
	float MoveDistanceRotations=distance/200*360;
	moveMotorTarget(Left, MoveDistanceRotations, 100);
	moveMotorTarget(Right, MoveDistanceRotations, 100);
};

bool TurnDegrees (float varTurnDegrees) {
	static bool InProgressTask;
	if (!InProgressTask) {
		resetGyro(Main_Gyro);
		if (varTurnDegrees>0) {
			setMotorSpeed(Left, 50);
			setMotorSpeed(Right, -50);
			} else {
			setMotorSpeed(Left, -50);
			setMotorSpeed(Right, 50);
		};
	};
	InProgressTask = true;
	if ((getGyroDegreesFloat(Main_Gyro)>varTurnDegrees && varTurnDegrees>0) || (getGyroDegreesFloat(Main_Gyro)<varTurnDegrees && varTurnDegrees<0)) {
		InProgressTask = false;
		setMotorSpeed(Left, 0);
		setMotorSpeed(Right, 0);
		return true;

	};
	return false;
};

void ArmHeightMove() {
	switch(ArmPresetValue) {  //moves the arm by reading the variable (ArmPresetValue)
	case 0://Floor
		setMotorTarget(ArmLeft, Height0, 100);
		setMotorTarget(ArmRight, Height0, 100);
		setTouchLEDColor(LED,colorOrange);
		break;

	case 1://Place HighScored Hub and Move MultiPusher Over Field Lines
		setMotorTarget(ArmLeft, Height1, 100);
		setMotorTarget(ArmRight, Height1, 100);
		setTouchLEDColor(LED,colorOrange);
		break;

	case 2://Position HighScored Hub
		setMotorTarget(ArmLeft, Height2, 100);
		setMotorTarget(ArmRight, Height2, 100);
		setTouchLEDColor(LED,colorOrange);
		break;

	case 3://Static Height / Moving height for balance
		setMotorTarget(ArmLeft, Height3, 100);
		setMotorTarget(ArmRight, Height3, 100);
		setTouchLEDColor(LED,colorOrange);
		break;

	case 4://Bonus Hub Align Position
		setMotorTarget(ArmLeft, Height4, 100);
		setMotorTarget(ArmRight, Height4, 100);
		setTouchLEDColor(LED,colorOrange);
		break;

	case 5://Bonus Hub Pickup Position
		setMotorTarget(ArmLeft, Height5, 100);
		setMotorTarget(ArmRight, Height5, 100);
		setTouchLEDColor(LED,colorOrange);
		break;

	};
};

void PickupBonusSequence () {
	static int LastState;
	bool P1;

	if (PickupBonusSequenceState !=LastState) {
		P1 = true;
		resetTimer(T1);
		LastState = PickupBonusSequenceState;
	}
	else {
		P1 = false;
	};
	switch (PickupBonusSequenceState){
	case 1:
		if (getJoystickValue(BtnEUp)==1) {
			PickupBonusSequenceState = 2;
		};
		break;

	case 2:
		if (P1) {
			driveDistance(600);
			ArmPresetValue=4;
			ArmHeightMove();
			delay(100);
		};
		if (getMotorZeroVelocity(Left)) {
			PickupBonusSequenceState = 3;
		};
		break;

	case 3:
		if (P1) {
			ArmPresetValue=5;
			ArmHeightMove();
			delay(100);
		};
		if (getMotorZeroVelocity(ArmLeft) || (getTimerValue(T1)>3000)) {
			PickupBonusSequenceState = 4;
		};
		break;

	case 4:
		if (P1) {
			driveDistance(-600);
			ArmPresetValue=3;
			delay(100);
		};
		if(getTimerValue(T1)>1500) {
			ArmHeightMove();
		};
		if (getMotorZeroVelocity(Left) || (getTimerValue(T1)>3000)) {
			PickupBonusSequenceState = 5;
		};
		break;

	case 5:
		if (TurnDegrees(90.0)) {
			PickupBonusSequenceState =1;
		};
		break;

	default: PickupBonusSequenceState = 1;
	};
};

void PlaceBonusSequence () {
	static int LastState;
	bool P1;

	if (PlaceBonusSequenceState !=LastState) {
		P1 = true;
		resetTimer(T1);
		LastState = PlaceBonusSequenceState;
	}
	else {
		P1 = false;
	};
	switch (PlaceBonusSequenceState){
	case 1:
		if (getJoystickValue(BtnFUp)==1) {
			PlaceBonusSequenceState = 2;
		};
		break;

	case 2:
		if (P1) {
			driveDistance(500);
			ArmPresetValue=3;
			ArmHeightMove();
			delay(100);
		};
		if (getMotorZeroVelocity(Left) || (getTimerValue(T1)>3000)) {
			PlaceBonusSequenceState = 3;
		};
		break;

	case 3:
		if (P1) {
			driveDistance(-70);
			delay(100);
		};
		if (getMotorZeroVelocity(Left) || (getTimerValue(T1)>1500)) {
			PlaceBonusSequenceState = 4;
		};
		break;

	case 4:
		if (P1) {
			ArmPresetValue=1;
			ArmHeightMove();
		};
		if (getMotorZeroVelocity(ArmLeft) || (getTimerValue(T1)>500)) {
			PlaceBonusSequenceState = 5;
		};
		break;

	case 5:
		if (P1) {
			delay(500);
			driveDistance(-380);
			delay(100);

		};
		if (getMotorZeroVelocity(Left) || (getTimerValue(T1)>1500)) {
			PlaceBonusSequenceState = 1;
		};
		if(getTimerValue(T1)>1500) {
			ArmPresetValue = 0;
			ArmHeightMove();
		};
		break;

	default: PlaceBonusSequenceState = 1;
	};
};

void ArmReset() {
	if (getBumperValue(ArmBottomBumper)==1) {
		resetMotorEncoder(ArmLeft);
		resetMotorEncoder(ArmRight);
		setTouchLEDColor(LED,colorBlue);
		setTouchLEDColor(LED,colorNone);
	}
}

task main() { // main program code
	resetMotorEncoder(ArmLeft);	 //Resets Left Arm Motor Encoder to 0
	resetMotorEncoder(ArmRight); //Resets Right Arm Motor Encoder to 0
	bool IndexArmPressed;
	intakeStarted = false;
	while(true) //while the program is running do this:
	{
		setTouchLEDColor(LED,colorNone);
		ArmReset();
		//Display Code
		displayTextLine(0, "Arm Height=%d", ((getMotorEncoder(ArmLeft)) + (getMotorEncoder(ArmRight)))/2); //Displays Average of motor encoders position
		displayVariableValues(1,ArmPresetValue); // displays the preset value for the height of the arm
		displayTextLine(2, "Gyro=%d", getGyroDegrees(Main_Gyro)); // displays the gyro value in degrees
		displayVariableValues(3, PickupBonusSequenceState);
		displayVariableValues(4, PlaceBonusSequenceState);
		displayVariableValues(5, Height0);
		//Sequences
		PickupBonusSequence();
		PlaceBonusSequence();
		//Preset Functions

		//Arm Code
		if (getJoystickValue(BtnLDown)==1 && IndexArmPressed==false) {  //gets the reading of LUP & LDOWN and turns it into a variable(ArmPresetValue)
			ArmPresetValue = (ArmPresetValue-1);
			ArmHeightMove();
			IndexArmPressed=true;
		}
		else {
			if (getJoystickValue(BtnLUp)==1 && IndexArmPressed==false) {
				ArmPresetValue = (ArmPresetValue+1);
				ArmHeightMove();
				IndexArmPressed=true;
			}
		};
		if (getJoystickValue(BtnLDown)==0 && getJoystickValue(BtnLUp)==0) {
			IndexArmPressed=false;
		};
		if (0>ArmPresetValue){
			ArmPresetValue = 0;
		}
		else {
			if (4<ArmPresetValue) {
				ArmPresetValue = 5;
			};
		}

		// Intake Code
		if (!intakeStarted) {
			waitUntil(getJoystickValue(BtnEDown));
		intakeStarted = true;
	}
		else if (!getJoystickValue(BtnEDown)) {
			setMotorSpeed(Intake, 100);
			} else if(getJoystickValue(BtnEDown)){
			setMotorSpeed(Intake, -100);
		};

		//Claw Code
		if (getJoystickValue(BtnRUp)) {
			setMotorSpeed(CubeClaw, 100);
			} else if (getJoystickValue(BtnRDown)) {
			setMotorSpeed(CubeClaw, -100);
			} else {
			setMotorSpeed(CubeClaw, 0);
		};

		//DriveCode
		if (PickupBonusSequenceState ==1 && PlaceBonusSequenceState == 1) {
			if(abs(getJoystickValue(ChA))>25 || abs(getJoystickValue(ChD))>25) {	//if the absoloute value of ChA is above 20 or the absoloute value of ChD is above 15 then allow the Motors to
				setMotorSpeed(Left, getJoystickValue(ChA)); //set the value of the motor to the value of the controller joystick
				setMotorSpeed(Right, getJoystickValue(ChD)); //set the value of the motor to the value of the controller joystick
			}
			else { setMotorSpeed(Left, 0);	// if nothing is happening on the controller set the motor speed to 0
				setMotorSpeed(Right, 0); // if nothing is happening on the controller set the motor speed to 0
			};
		};
	};
}

//END
