#pragma config(UserModel, "E:/VIQC Code/Lib/Header.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/***********************************************************************************************/
//																			Setup Code																							/
/***********************************************************************************************/
float Height0 = 0; //
float Height1 = 0; //
float Height2 = 0; //
float Height3 = 0; //
float Height4 = 0; //
float Height5 = 0; //
int ArmPresetValue = 0; // the preset number that tells the preset code how high to move the arm

bool overTemp; // if any of the motors are overtemp set this value to true
bool currentLimitFlag; // if any of the motors are using current above the default value set this value to true

int PickupBonusSequenceState;
int PlaceBonusSequenceState;

/***********************************************************************************************/
//																			Functions																							  /
/***********************************************************************************************/
// Simple Drive Command/Function in MM
void driveDistance(float distance) {
	float MoveDistanceRotations=distance/200;

	setMotorTarget(Left, MoveDistanceRotations, 100);
	setMotorTarget(Right, MoveDistanceRotations, 100);
};

// Simple Turning Function with P controller
bool TurnDegrees (float varTurnDegrees) {
	if (varTurnDegrees>0) {
		setMotorSpeed(Left, 50);
		setMotorSpeed(Right, -50);
		if (getGyroDegrees(Main_Gyro)>varTurnDegrees) {
		}
		return false;
		} else {
		setMotorSpeed(Left, -50);
		setMotorSpeed(Right, 50);
		if (getGyroDegrees(Main_Gyro)<varTurnDegrees) {
			return false;
		}
	}
	return true;
}

//Driver-Control Style Selection Function
void LeftD (){
	arcadeControl(ChB, ChA, 15);
	armControl(ArmLeft, BtnLUp, BtnLDown, 100);
	armControl(ArmRight, BtnLUp, BtnLDown, 100);
	displayText(0, "LeftDrive");
};
void RightD (){
	armControl(ArmLeft, BtnLUp, BtnLDown, 100);
	armControl(ArmRight, BtnLUp, BtnLDown, 100);
	displayText(0, "RightDrive");
	//arcadeControl(ChC, ChD, 15);
	// RawCod

	float RightSpeed;
	float LeftSpeed;

	if(abs(vexRT[ChD]) <= abs(15) && abs(vexRT[ChC]) <= abs(15))
	{
		RightSpeed = 0;
		LeftSpeed	= 0;
	}
	else
	{
		RightSpeed= ((getJoystickValue(ChD) - getJoystickValue(ChC))/2);
		LeftSpeed = ((getJoystickValue(ChD) + getJoystickValue(ChC))/2);

		if(nGlobalJoyScaledValue != nMaxJoyScaleValue)
		{
			RightSpeed = RightSpeed * (nGlobalJoyScaledValue / 100.0);
			LeftSpeed 	= LeftSpeed * (nGlobalJoyScaledValue / 100.0);
			setMotorSpeed(Right,RightSpeed);
			setMotorSpeed(Left,LeftSpeed);
		}
	}

};

void SplitLeftD (){
	arcadeControl(ChC, ChA, 15);
	armControl(ArmLeft, BtnLUp, BtnLDown, 100);
	armControl(ArmRight, BtnLUp, BtnLDown, 100);
	displayText(0, "Split L");
};
void SplitRightD (){
	arcadeControl(ChB, ChD, 15);
	armControl(ArmLeft, BtnLUp, BtnLDown, 100);
	armControl(ArmRight, BtnLUp, BtnLDown, 100);
	displayText(0, "Split R");
};
void TankD (){
	if(abs(getJoystickValue(ChA))>25 || abs(getJoystickValue(ChD))>25) {	//if the absoloute value of ChA is above 20 or the absoloute value of ChD is above 15 then allow the Motors to
		setMotorSpeed(Left, getJoystickValue(ChA)); //set the value of the motor to the value of the controller joystick
		setMotorSpeed(Right, getJoystickValue(ChD)); //set the value of the motor to the value of the controller joystick
	}
	else { setMotorSpeed(Left, 0);	// if nothing is happening on the controller set the motor speed to 0
		setMotorSpeed(Right, 0); // if nothing is happening on the controller set the motor speed to 0
	};
	armControl(ArmLeft, BtnLUp, BtnLDown, 100);
	armControl(ArmRight, BtnLUp, BtnLDown, 100);
	displayText(0, "Tank");
};


void DriveSelect (float DriveStyle) {

	if (DriveStyle == 1) { // Left Control
		LeftD();
		} else if (DriveStyle == 2) { // Right Control
		RightD();
		} else if  (DriveStyle == 3) { // Split Left Control
		SplitLeftD();
		} else if  (DriveStyle == 4) { // Split Right Control
		SplitRightD();
		} else if  (DriveStyle == 5) { // Tank Control
		TankD();
	};
};

//E-STOP AND MOTOR DIAGNOSTICS
void ESTOP (float delay) { // if emergency stop buttons are pushed stop all motor and blink red on touch led
	if ((getJoystickValue(BtnEDown)&&(getJoystickValue(BtnFDown) ) || (overTemp==true)||(currentLimitFlag==true))) {
		sleep(delay);
		repeatUntil(getTouchLEDValue(LED)==1 || (getJoystickValue(BtnEDown)==1) || (getJoystickValue(BtnFDown)==1)) {
			setTouchLEDColor(LED,colorRed);
			setTouchLEDBlinkTime(LED, 12.5, 7.5);
			stopAllMotors();
			playSound(soundCarAlarm2);
			Height0 = 0; //Floor
			Height1 = 0; //Place HighScored Hub and Move MultiPusher Over Field Lines
			Height2 = 0; //Position HighScored Hub
			Height3 = 0; //Static Height / Moving height for balance
			Height4 = 0; //Bonus Hub Position
			Height5 = 0; //Bonus Hub PickUp
			int ArmPresetValue = 0; // the preset number that tells the preset code how high to move the arm
		};
		setMotorTarget(ArmLeft, Height1, 100);
		setMotorTarget(ArmRight, Height1, 100);
		sleep(1000);
		while (getBumperValue(ArmBottomBumper)==false) {
			setMotorTarget(ArmLeft, Height0, 75);
			setMotorTarget(ArmRight, Height0, 75);
		};
		resetMotorEncoder(ArmLeft);
		resetMotorEncoder(ArmRight);
		setTouchLEDColor(LED, colorNone);
	};
};

void MotorD() { // checks for motor overtemp or currentLimitFlag and plays an alarm if they are true
	if ((overTemp==true)|(currentLimitFlag==true))
		playSound(soundCarAlarm2);
};


void ArmHeightMove() {
	switch(ArmPresetValue) {  //moves the arm by reading the variable (ArmPresetValue)
	case 0://Floor
		setMotorTarget(ArmLeft, Height0, 100);
		setMotorTarget(ArmRight, Height0, 100);
		setTouchLEDColor(LED,colorOrange);
		setTouchLEDColor(LED,colorNone);
		break;

	case 1://Place HighScored Hub and Move MultiPusher Over Field Lines
		setMotorTarget(ArmLeft, Height1, 100);
		setMotorTarget(ArmRight, Height1, 100);
		setTouchLEDColor(LED,colorOrange);
		setTouchLEDColor(LED,colorNone);
		break;

	case 2://Position HighScored Hub
		setMotorTarget(ArmLeft, Height2, 100);
		setMotorTarget(ArmRight, Height2, 100);
		setTouchLEDColor(LED,colorOrange);
		setTouchLEDColor(LED,colorNone);
		break;

	case 3://Static Height / Moving height for balance
		setMotorTarget(ArmLeft, Height3, 100);
		setMotorTarget(ArmRight, Height3, 100);
		setTouchLEDColor(LED,colorOrange);
		setTouchLEDColor(LED,colorNone);
		break;

	case 4://Bonus Hub Align Position
		setMotorTarget(ArmLeft, Height4, 100);
		setMotorTarget(ArmRight, Height4, 100);
		setTouchLEDColor(LED,colorOrange);
		setTouchLEDColor(LED,colorNone);
		break;

	case 5://Bonus Hub Pickup Position
		setMotorTarget(ArmLeft, Height5, 100);
		setMotorTarget(ArmRight, Height5, 100);
		setTouchLEDColor(LED,colorOrange);
		setTouchLEDColor(LED,colorNone);
		break;

	};
};

void ArmTopLimit() {
	if (getBumperValue(ArmTopBumper)==1 && getJoystickValue(BtnRUp)){
		stopMultipleMotors(ArmLeft, ArmRight);
	};
};
void PickupBonusSequence () {
	static int LastState;
	bool P1;

	if (PickupBonusSequenceState !=LastState) {
		P1 = true;
		resetTimer(T1);
		LastState = PickupBonusSequenceState;
	}
	else {
		P1 = false;
	};
	switch (PickupBonusSequenceState){
	case 1:
		if (getJoystickValue(BtnEUp)==1) {
			PickupBonusSequenceState = 2;
		};
		break;

	case 2:
		if (P1) {
			driveDistance(600);
			ArmPresetValue=4;
			ArmHeightMove();
			delay(100);
		};
		if (getMotorZeroVelocity(Left)) {
			PickupBonusSequenceState = 3;
		};
		break;

	case 3:
		if (P1) {
			ArmPresetValue=5;
			ArmHeightMove();
			delay(100);
		};
		if (getMotorZeroVelocity(ArmLeft) || (getTimerValue(T1)>3000)) {
			PickupBonusSequenceState = 4;
		};
		break;

	case 4:
		if (P1) {
			driveDistance(-600);
			ArmPresetValue=3;
			delay(100);
		};
		if(getTimerValue(T1)>1500) {
			ArmHeightMove();
		};
		if (getMotorZeroVelocity(Left) || (getTimerValue(T1)>3000)) {
			PickupBonusSequenceState = 5;
		};
		break;

	case 5:
		if (TurnDegrees(90.0)) {
			PickupBonusSequenceState =1;
		};
		break;

	default: PickupBonusSequenceState = 1;
	};
};

void PlaceBonusSequence () {
	static int LastState;
	bool P1;

	if (PlaceBonusSequenceState !=LastState) {
		P1 = true;
		resetTimer(T1);
		LastState = PlaceBonusSequenceState;
	}
	else {
		P1 = false;
	};
	switch (PlaceBonusSequenceState){
	case 1:
		if (getJoystickValue(BtnFUp)==1) {
			PlaceBonusSequenceState = 2;
		};
		break;

	case 2:
		if (P1) {
			driveDistance(500);
			ArmPresetValue=3;
			ArmHeightMove();
			delay(100);
		};
		if (getMotorZeroVelocity(Left) || (getTimerValue(T1)>3000)) {
			PlaceBonusSequenceState = 3;
		};
		break;

	case 3:
		if (P1) {
			driveDistance(-70);
			delay(100);
		};
		if (getMotorZeroVelocity(Left) || (getTimerValue(T1)>1500)) {
			PlaceBonusSequenceState = 4;
		};
		break;

	case 4:
		if (P1) {
			ArmPresetValue=1;
			ArmHeightMove();
		};
		if (getMotorZeroVelocity(ArmLeft) || (getTimerValue(T1)>500)) {
			PlaceBonusSequenceState = 5;
		};
		break;

	case 5:
		if (P1) {
			delay(500);
			driveDistance(-380);
			delay(100);

		};
		if (getMotorZeroVelocity(Left) || (getTimerValue(T1)>1500)) {
			PlaceBonusSequenceState = 1;
		};
		if(getTimerValue(T1)>1500) {
			ArmPresetValue = 0;
			ArmHeightMove();
		};
		break;

	default: PlaceBonusSequenceState = 1;
	};
};
/***********************************************************************************************/
//																			Auton Code																							/
/***********************************************************************************************/

void AutonSelect(float Variations) {
	if (getJoystickValue(BtnEUp) && getJoystickValue(BtnFUp))	{
		switch (Variations) {
		case 1:
			displayText(1, "AutonStarted ");
			displayText(2, "Variation: Hang");
			driveDistance(550);
			delay(5000);
			setMotorTarget(ArmLeft,-680, 60);
			setMotorTarget(ArmRight,-680, 60);
			delay(1000);
			driveDistance(-100);
			delay(1000);
			while(true) {
				setMotorSpeed(ArmLeft, 100);
				setMotorSpeed(ArmRight, 100);
			};

			break;


		case 2:
			resetMotorEncoder(ArmLeft);  //Resets Left Arm Motor Encoder to 0

			resetMotorEncoder(ArmRight); //Resets Right Arm Motor Encoder to 0

			while(true) {//while the program is running do this:
				displayText(1, "AutonStarted ");
				displayText(2, "Variation: Bonus and Hang");
				resetGyro(Main_Gyro);
				while(TurnDegrees(-35)){};
				driveDistance(400);
				delay(5000);
				setMotorTarget(ArmLeft,-680, 60);
				setMotorTarget(ArmRight,-680, 60);
				delay(3000);
				driveDistance(-400);
				delay(5000);
				resetGyro(Main_Gyro);
				while(TurnDegrees(35)){};
				delay(5000);
				driveDistance(550);
				delay(5000);
				setMotorTarget(ArmLeft,-680, 60);
				setMotorTarget(ArmRight,-680, 60);
				delay(1000);
				driveDistance(-100);
				delay(1000);
				while(true) {
					setMotorSpeed(ArmLeft, 100);
					setMotorSpeed(ArmRight, 100);
				};
			};
			break;

		case 3:
			resetMotorEncoder(ArmLeft);  //Resets Left Arm Motor Encoder to 0
			resetMotorEncoder(ArmRight); //Resets Right Arm Motor Encoder to 0

			while(true) //while the program is running do this:
			{

				//Display Code
				displayTextLine(0, "Arm=%d", ((getMotorEncoder(ArmLeft)) + (getMotorEncoder(ArmRight)))/2); //Displays Average of motor encoders position
				displaySensorValues(3, Main_Gyro);
				displayText(1, "AutonStarted ");
				displayText(2, "Variation: ?????");
				//Autonomous Code
				moveMotorTarget(Left, 200, 50);
				moveMotorTarget(Right, 720, 50);
				wait(1, seconds);
				moveMotorTarget(Left, 366.5, 50);
				moveMotorTarget(Right,-366.5, 50);
				wait(1, seconds);
				moveMotorTarget(Left, 360, 50);
				moveMotorTarget(Right, 360, 50);
				wait(1, seconds);
				moveMotorTarget(Left, 1080, 50);
				moveMotorTarget(Right, 1080, 50);
				wait(1, seconds);
				moveMotorTarget(Left, -366.5, 50);
				moveMotorTarget(Right, 366.5, 50);
				wait(1, seconds);
				moveMotorTarget(Left, 1080, 50);
				moveMotorTarget(Right, 1080, 50);
				setMultipleMotors(50,ArmLeft, ArmRight);
				wait(1.5, seconds);
				moveMotorTarget(Left, -360, 50);
				moveMotorTarget(Right, -360, 50);

				break;
			}
			break;

		case 4:
			displayText(1, "AutonStarted ");
			displayText(2, "Variation: Test");

			while(true) //while the program is running do this:
			{
				while(TurnDegrees(45)){};
				while(true){wait(100);};
			}
			break;

		};
	};
}

/***********************************************************************************************/
//																			Odometry Code																					  /
/***********************************************************************************************/

float xaxisPos = 0;
float yaxisPos = 0;
float robotAngle = 0;
float robotPosition = 0;
float dL = 0;
float dR = 0;



int ticksPerRev = 360;
float diameter = 2.5;
float radius = 1.25;
float calibration = 3.14159265429*diameter/ticksPerRev; //C our calibration factor 2:11 video
float avcR = 0.218166156547917;
float avcL = 0.218166156547917;
float distanceBetweenWheels = 7.25; // B (base line distance)
float Test1;
float Test2;
task odomTask()
{
	while(true)
	{
		setMotorEncoderUnits(encoderCounts);
		dR = calibration * getMotorEncoder(Right);
		dL = calibration * getMotorEncoder(Left);
		robotPosition = (dR+dL) / 2;
		robotAngle = (dL-dR) / distanceBetweenWheels * (180/3.14159265429);
		xaxisPos = radius/2 * (dR + dL) * sin(robotAngle);
		yaxisPos = radius/2 * (dR + dL) * cos(robotAngle);
		Test1 = atan(xaxisPos);
		Test2 = atan(yaxisPos);

		/*	displayVariableValues(line1,xaxisPos);
		displayVariableValues(line2,yaxisPos);
		displayVariableValues(line3,robotPosition);
		displayVariableValues(line4, robotAngle);
		displayVariableValues(line5, getGyroDegreesFloat(Main_Gyro));
		*/

		if(abs(getJoystickValue(ChA))>25 || abs(getJoystickValue(ChD))>25) {	//if the absoloute value of ChA is above 20 or the absoloute value of ChD is above 15 then allow the Motors to
			setMotorSpeed(Left, getJoystickValue(ChA)); //set the value of the motor to the value of the controller joystick
			setMotorSpeed(Right, getJoystickValue(ChD)); //set the value of the motor to the value of the controller joystick
		}
		else { setMotorSpeed(Left, 0);	// if nothing is happening on the controller set the motor speed to 0
			setMotorSpeed(Right, 0); // if nothing is happening on the controller set the motor speed to 0
		};
		armControl(ArmLeft, BtnLUp, BtnLDown, 100);
		armControl(ArmRight, BtnLUp, BtnLDown, 100);

		datalogAddValueWithTimeStamp (1, xaxisPos);
		datalogAddValueWithTimeStamp (2, yaxisPos);

		if (getJoystickValue(BtnLDown)) {
			forward(10, rotations, 50);
		}
		else if (getJoystickValue(BtnLUp)) {
			turnLeft(90, degrees, 40);
			delay(20);
			forward(10, rotations, 50);
		}
	}
}
/***********************************************************************************************/
//																			Main Code																							  /
/***********************************************************************************************/

task main()
{
	while (true) {
		//Driving
		DriveSelect(5);
		AutonSelect(4);

		//Safety and Analysing
		ESTOP(0);
		MotorD();
			//StartTask(odomTask);

		//Sequences
		PickupBonusSequence();
		PlaceBonusSequence();

	};
}
