			//2
			ArmPresetValue=3;
			ArmHeightMove();
			delay(100);
			GrabCube();
			//3
			driveDistance(220);
			delay(1000);
			ArmPresetValue=2;
			ArmHeightMove();
			delay(400);
			//4
			ReleaseCube();
			delay(400);
			driveDistance(-200);
			//5
			delay(800);
			ArmPresetValue=0;
			ArmHeightMove();
			delay(800);
