#pragma config(Motor,  motor1,          LiftLeft,      tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor2,          LiftRight,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          Claw,          tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor10,         Left,          tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         Hook,          tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         Right,         tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// btrwnicholas@gmail.com
/////////////////////////////////////////////////////////
task main()
{
	//SET MOTORS TO BRAKE MODE
	setMotorBrakeMode(LiftLeft, motorHold);
	setMotorBrakeMode(LiftRight, motorHold);
	setMotorBrakeMode(Hook, motorHold);
	setMotorBrakeMode(Claw, motorHold);
	setMotorBrakeMode(Left, motorHold);
	setMotorBrakeMode(Right, motorHold);
	//RESET MOTOR ENCODERS
	while(true) {
		arcadeControl(ChA, ChC, 25);

		//Hook Code
		if (getJoystickValue(BtnLUp)) {
			setMotorSpeed(Hook, -90);
			} else if (getJoystickValue(BtnLDown)) {
			setMotorSpeed(Hook, 90);
			} else {
			setMotorSpeed(Hook, 0);
		};

		if (getJoystickValue(BtnEUp)) {
			setMotorSpeed(Claw, -90);
			} else if (getJoystickValue(BtnEDown)) {
			setMotorSpeed(Claw, 90);
			} else {
			setMotorSpeed(Claw, 0);
		};

				if (getJoystickValue(BtnRUp)) {
			setMultipleMotors(LiftLeft, LiftRight, 100);
			} else if (getJoystickValue(BtnRDown)) {
			setMotorSpeed(Claw, 80);
			} else {
			setMotorSpeed(Claw, 0);
		};
		///////////////////////
	};
};
