//gyro Drft
long gyroValue;
long gyroError;


task gyroTask()
{
 long rate;
 long angle, lastAngle;
 lastAngle = 0;
 gyroError=0;
 // Change sensitivity, this allows the rate reading to be higher
 setGyroSensitivity(Gyro, gyroNormalSensitivity);
 //Reset the gyro sensor to remove any previous data.
 resetGyro(Gyro);
 wait1Msec(1000);
 repeat (forever) {
  rate = getGyroRate(Gyro);
  angle = getGyroDegrees(Gyro);
  // If big rate then ignore gyro changes
  if( abs( rate ) < 2 )
  {
   if( angle != lastAngle )
    gyroError += lastAngle - angle;
  }
  lastAngle = angle;
  gyroValue = angle + gyroError;
  wait1Msec(10);
 }
}


task main()
{

 startTask( gyroTask );

 repeat (forever) {
  tankControl(ChD, ChA, 10);
  armControl(armMotor, BtnLUp, BtnLDown, 75);
  armControl(clawMotor, BtnRDown, BtnRUp, 75);

  int MyGyroValue=gyroValue;

  }
}


// Keep Straight

config(Sensor, port1,  Gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port2,  LeftLED,        sensorVexIQ_LED)
#pragma config(Motor,  motor3,          RightDrive,    tmotorVexIQ, PIDControl, driveRight, encoder)
#pragma config(Motor,  motor6,          LeftDrive,     tmotorVexIQ, PIDControl, reversed, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int MotorTarget,MotorSpeed,SpeedLeft=0,SpeedRight=0,SpeedSide=0,Heading=0, ArmHeight=0,HeadingStraight;

long gyroValue;
long gyroError;


task gyroTask()
{
 long rate;
 long angle, lastAngle;
 lastAngle = 0;
 gyroError=0;
 // Change sensitivity, this allows the rate reading to be higher
 setGyroSensitivity(Gyro, gyroNormalSensitivity);
 //Reset the gyro sensor to remove any previous data.
 resetGyro(Gyro);
 wait1Msec(1000);
 repeat (forever) {
  rate = getGyroRate(Gyro);
  angle = getGyroDegrees(Gyro);
  // If big rate then ignore gyro changes
  if( abs( rate ) < 2 )
  {
   if( angle != lastAngle )
    gyroError += lastAngle - angle;
  }
  lastAngle = angle;
  gyroValue = angle + gyroError;
  wait1Msec(10);
 }
}


task keepStraight(){
 while(true) {
  HeadingStraight=0;
  if(gyroValue<-2){HeadingStraight=-6;}
  if(gyroValue>2){HeadingStraight=6;}
  wait1Msec(100);
  setMotorSpeed(LeftDrive, SpeedLeft-HeadingStraight);
  setMotorSpeed(RightDrive,SpeedRight +HeadingStraight);
}}




task main()
{
 startTask( gyroTask );

 setGyroSensitivity(Gyro, gyroNormalSensitivity);
 resetGyro(Gyro);
 wait1Msec(1000);

  //Start autonomous by touching LED
 waitUntil(getTouchLEDValue(LeftLED) == 1);
  //Colour LEDs
 setTouchLEDColor(LeftLED,colorRed);
 setTouchLEDBlinkTime(LeftLED, 10, 20);

 //straight ahead, with gyro compensation
 SpeedLeft=50;
 SpeedRight=50;
 startTask(keepStraight);
 waitUntil (getMotorEncoder(LeftDrive)>1260);//Forward 3.5 rotations
 stopTask(keepStraight);
 stopMultipleMotors(LeftDrive,RightDrive);

 // turn
 setMotor(LeftDrive, 30);
 setMotor(RightDrive, -30);
 waitUntil (gyroValue > 85);
 stopMultipleMotors(LeftDrive,RightDrive);
 wait1Msec(500);


}
